# Generated by Django 2.2.11 on 2020-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueEntity',
            fields=[
                ('EId', models.IntegerField(primary_key=True, serialize=False)),
                ('Entity', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueIntent',
            fields=[
                ('IId', models.IntegerField(primary_key=True, serialize=False)),
                ('Intent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('RId', models.IntegerField(primary_key=True, serialize=False)),
                ('Response', models.TextField()),
                ('Entity_id', models.ForeignKey(db_column='Entity_id', default=0, on_delete='true', to='chat.UniqueEntity')),
                ('Intent_id', models.ForeignKey(db_column='Intent_id', default=0, on_delete='true', to='chat.UniqueIntent')),
            ],
        ),
    ]
