# Generated by Django 2.2.11 on 2020-03-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('ddu_reporting_date', models.CharField(blank=True, max_length=30, null=True)),
                ('admission_type', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_format', models.CharField(default='LFM', max_length=30)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=30, null=True)),
                ('acpc_seat_allotment_date', models.DateTimeField(blank=True, null=True)),
                ('is_d2d', models.CharField(blank=True, max_length=30, null=True)),
                ('enrollment_year', models.CharField(blank=True, max_length=30, null=True)),
                ('degree', models.CharField(blank=True, max_length=30, null=True)),
                ('qualifying_exam_rollno', models.CharField(blank=True, max_length=30, null=True)),
                ('session_type', models.CharField(blank=True, max_length=30, null=True)),
                ('session_no', models.CharField(blank=True, max_length=30, null=True)),
                ('batch_year', models.CharField(blank=True, max_length=30, null=True)),
                ('old_student_code', models.CharField(blank=True, max_length=30, null=True)),
                ('students_allotment', models.CharField(blank=True, max_length=30, null=True)),
                ('merit_rank', models.IntegerField(blank=True, default=0, null=True)),
                ('re_shuffle_status', models.CharField(blank=True, max_length=30, null=True)),
                ('re_shuffle_phase', models.IntegerField(blank=True, default=0, null=True)),
                ('cast_category_code', models.CharField(blank=True, max_length=30, null=True)),
                ('sub_cast', models.CharField(blank=True, max_length=30, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=30, null=True)),
                ('mother_tongue', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=30, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=30, null=True)),
                ('relation_type', models.CharField(blank=True, max_length=30, null=True)),
                ('full_name', models.CharField(blank=True, max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=30, null=True)),
                ('annual_income', models.IntegerField(blank=True, default=0, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('address3', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('local_address1', models.CharField(blank=True, max_length=30, null=True)),
                ('local_address2', models.CharField(blank=True, max_length=30, null=True)),
                ('local_address3', models.CharField(blank=True, max_length=30, null=True)),
                ('local_city', models.CharField(blank=True, max_length=30, null=True)),
                ('local_mobile_no', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
