# Generated by Django 2.2.11 on 2020-04-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subject_id', models.CharField(max_length=5, primary_key='true', serialize=False)),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_credit', models.BigIntegerField()),
                ('subject_secured_score', models.BigIntegerField(default=0)),
                ('subject_total_score', models.BigIntegerField()),
                ('subject_grade', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ddu_reporting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='session_no',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpi', models.BigIntegerField(default=0.0)),
                ('spi', models.BigIntegerField(default=0.0)),
                ('overall_grade', models.CharField(default='', max_length=10)),
                ('subject', models.ManyToManyField(to='login.subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.ManyToManyField(to='login.semester'),
        ),
    ]
