# Generated by Django 2.2.11 on 2020-04-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200405_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('batch_year', models.CharField(max_length=10)),
                ('attempt_type', models.CharField(max_length=10)),
                ('session_no', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Course')),
            ],
        ),
        migrations.CreateModel(
            name='RegularResult',
            fields=[
                ('result_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('extarnal_marks', models.IntegerField(default=0)),
                ('sessional_marks', models.IntegerField(default=0)),
                ('practical_marks', models.IntegerField(default=0)),
                ('termwork_marks', models.IntegerField(default=0)),
                ('max_marks', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Student')),
            ],
        ),
        migrations.CreateModel(
            name='InternalResult',
            fields=[
                ('result_id', models.CharField(max_length=30, primary_key='true', serialize=False)),
                ('sess1_att', models.IntegerField(default=0)),
                ('sess1_marks', models.IntegerField(default=0)),
                ('lecture_Att1', models.IntegerField(default=0)),
                ('lecture_Att1_out_of', models.IntegerField(default=0)),
                ('pr_Att1', models.IntegerField(default=0)),
                ('pr_Att1_out_of', models.IntegerField(default=0)),
                ('sess2_att', models.IntegerField(default=0)),
                ('sess2_marks', models.IntegerField(default=0)),
                ('lecture_Att2', models.IntegerField(default=0)),
                ('lecture_Att2_out_of', models.IntegerField(default=0)),
                ('pr_Att2', models.IntegerField(default=0)),
                ('pr_Att2_out_of', models.IntegerField(default=0)),
                ('sess3_att', models.IntegerField(default=0)),
                ('sess3_marks', models.IntegerField(default=0)),
                ('lecture_Att3_out_of', models.IntegerField(default=0)),
                ('lecture_Att3', models.IntegerField(default=0)),
                ('pr_Att3', models.IntegerField(default=0)),
                ('pr_Att3_out_of', models.IntegerField(default=0)),
                ('block_att', models.IntegerField(default=0)),
                ('block_marks', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Student')),
            ],
        ),
    ]
