# Generated by Django 2.2.11 on 2020-04-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_exam_internalresult_regularresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sess_min_pass3',
            new_name='pr_min_pass2',
        ),
        migrations.AddField(
            model_name='course',
            name='sess_min_pass2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='tw_min_pass2',
            field=models.IntegerField(default=0),
        ),
    ]
