# Generated by Django 2.2.11 on 2020-04-05 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200405_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Program'),
        ),
    ]
