# Generated by Django 2.2.11 on 2020-04-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200405_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(default='2020-05-05'),
            preserve_default=False,
        ),
    ]
