# Generated by Django 2.2.11 on 2020-04-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
    ]
