# Generated by Django 2.2.11 on 2020-04-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_exam_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
    ]
