# Generated by Django 2.2.11 on 2020-04-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200412_1412'),
        ('login', '0008_remove_exam_date'),
    ]

    operations = [
    ]
