# Generated by Django 2.2.11 on 2020-04-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_merge_20200412_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateTimeField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
