# Generated by Django 2.2.11 on 2020-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20200412_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.RemoveField(
            model_name='internalresult',
            name='id',
        ),
        migrations.RemoveField(
            model_name='regularresult',
            name='id',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(default='EX00', max_length=30, primary_key='true', serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internalresult',
            name='result_id',
            field=models.CharField(default='RS00', max_length=30, primary_key='true', serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regularresult',
            name='result_id',
            field=models.CharField(default='RS00', max_length=30, primary_key='true', serialize=False),
            preserve_default=False,
        ),
    ]
